### ISSUE TITLE
"Other" Clear type doesn't work

### ISSUE THREAD

**Issue by ghost** [asso-msn/coffee-break#1]
pretty much what the title says. If I try to use other it just doesn't show up. Also worth noting that if I pick another type after other they both become selected somehow.

**Comment by ghost** [comment]
oh, here's a screenshot of it. I probably should've put this here to begin with
![chrome_2020-12-09_18-54-58](https://user-images.githubusercontent.com/38615745/101703087-2c4d7300-3a50-11eb-8423-9fd72ccccd79.png)

**Comment by Tina-otoge** [comment]
Ah yeah, the form does not work very great, I'm most certainly sure it works by calling the API as I have some apps that rely on this and works.

I'll look into making it work from the website 👍

**Comment by ghost** [comment]
so it only selects one now, but if I pick other it still doesn't show up on the card. not sure if I'm just doing it wrong now or something

just as an example here:
https://coffee.tina.moe/api/generate?username=Funguy161&player_code=&rank=%E2%98%85%E2%98%85%E2%98%85%E2%98%85%E2%98%85+Star&avatar=https%3A%2F%2Ftr.rbxcdn.com%2Fdc5e3bf34d649ef237d99e24cd9b30d3%2F150%2F150%2FAvatarHeadshot%2FPng&playstyle-other=&profile_extras=&game=RoBeats&title=Nyan+Cat+%28NewCity+Remix%29&subtitle=&artist=daniwell&subartist=&genre=&bpm=&jacket=https%3A%2F%2Fstatic.wikia.nocookie.net%2Frobeats%2Fimages%2F9%2F98%2FNyan_cat_hard.png%2Frevision%2Flatest%2Fscale-to-width-down%2F310%3Fcb%3D20190220085426&mode-other=&level=19&difficulty=Hard&notes_count=&max_chart_combo=&creator=&mods=&clear_type=_other&clear-type-other=NO-MISS+CLEAR&score=1%2C284%2C792&grade=A&accuracy=94.09&hp=&max_combo=911&breaks=&pp=&judges=%7B%22PERFECT%22%3A+702%2C+%22GREAT%22%3A+210%2C+%22OKAY%22%3A+2%2C+%22MISS%22%3A+0%7D&date=2020-12-27&copyright=&class=%7B%22rank%22%3A+%22rainbow%22%2C+%22grade%22%3A+%22blue%22%2C+%22avatar%22%3A+%22round%22%2C+%22level%22%3A+%22orange%22%7D&settings=

The other clear is in the URL (so it is going through, I think?) but it's not on the card

**Comment by Tina-otoge** [comment]
This should be good now, loading your link correctly shows "NO-MISS CLEAR" now.
Make sure to force refresh with CTRL+F5 if your browser kept a copy of the previous card in cache.

**Comment by ghost** [comment]
Yup it works now. Very cool, thank you
